/**
 * PoC: Canton transaction_uuid / preparedTransactionHash correlation.
 *
 * Tests whether the user can get a unique identifier BEFORE tx execution
 * that the MPC can later observe in the committed transaction logs.
 *
 * Flow:
 *   1. Setup: sandbox, parties, VaultOrchestrator
 *   2. User: prepare a RequestEvmDeposit exercise → get preparedTransactionHash + transaction_uuid
 *   3. User: execute the prepared transaction → submit to chain
 *   4. MPC:  observe the update stream → check for preparedTransactionHash / transaction_uuid
 *   5. Verify: user-provided value == MPC-observed value
 *
 * Run:
 *   pnpm daml:sandbox  (in another terminal)
 *   pnpm tx-uuid-poc
 */

import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import createClient from "openapi-fetch";
import type { paths, components } from "../../generated/api/ledger-api.js";
import {
  uploadDar,
  allocateParty,
  createUser,
  createContract,
  exerciseChoice,
  getLedgerEnd,
  getUpdates,
  BASE_URL,
} from "../infra/canton-client.js";
import { VaultOrchestrator } from "@daml.js/canton-mpc-poc-0.0.1/lib/Erc20Vault/module";
import { deriveDepositAddress, chainIdHexToCaip2 } from "../mpc/address-derivation.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DAR_PATH = resolve(__dirname, "../../../.daml/dist/canton-mpc-poc-0.0.1.dar");
const VAULT_ORCHESTRATOR = VaultOrchestrator.templateId;
const USER_ID = "tx-uuid-poc";

const MPC_ROOT_PUBLIC_KEY =
  "04bb50e2d89a4ed70663d080659fe0ad4b9bc3e06c17a227433966cb59ceee020decddbf6e00192011648d13b1c00af770c0c1bb609d4d3a5c98a43772e0e18ef4";
const MPC_PUB_KEY_SPKI =
  "3056301006072a8648ce3d020106052b8104000a03420004bb50e2d89a4ed70663d080659fe0ad4b9bc3e06c17a227433966cb59ceee020decddbf6e00192011648d13b1c00af770c0c1bb609d4d3a5c98a43772e0e18ef4";

const client = createClient<paths>({ baseUrl: BASE_URL });

function packageIdFromTemplateId(templateId: string): string {
  const packageId = templateId.split(":")[0];
  if (!packageId) throw new Error(`Invalid templateId: ${templateId}`);
  return packageId;
}

function buildSampleEvmParams(vaultAddress: string) {
  return {
    to: "a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    functionSignature: "transfer(address,uint256)",
    args: [
      vaultAddress.slice(2).padStart(64, "0"),
      "0000000000000000000000000000000000000000000000000000000005f5e100",
    ],
    value: "0000000000000000000000000000000000000000000000000000000000000000",
    nonce: "0000000000000000000000000000000000000000000000000000000000000001",
    gasLimit: "000000000000000000000000000000000000000000000000000000000000c350",
    maxFeePerGas: "00000000000000000000000000000000000000000000000000000000dcd65000",
    maxPriorityFee: "000000000000000000000000000000000000000000000000000000003b9aca00",
    chainId: "0000000000000000000000000000000000000000000000000000000000aa36a7",
  };
}

/**
 * Extract all UUIDs from a base64-encoded PreparedTransaction protobuf.
 * The protobuf contains:
 *   - commandId (in SubmitterInfo) — the one the user sent
 *   - transaction_uuid (in Metadata) — generated by the prepare endpoint
 * Without a protobuf parser, we search for UUID-shaped strings in the decoded bytes.
 */
function extractAllUuids(preparedTransactionBase64: string): string[] {
  const buf = Buffer.from(preparedTransactionBase64, "base64");
  const text = buf.toString("utf8");

  const uuidPattern = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;
  return [...new Set(text.match(uuidPattern) ?? [])];
}

/**
 * Dump readable strings from a base64-encoded protobuf for inspection.
 */
function dumpReadableStrings(base64: string): string[] {
  const buf = Buffer.from(base64, "base64");
  const readable: string[] = [];
  let current = "";
  for (const byte of buf) {
    if (byte >= 0x20 && byte < 0x7f) {
      current += String.fromCharCode(byte);
    } else {
      if (current.length >= 4) readable.push(current);
      current = "";
    }
  }
  if (current.length >= 4) readable.push(current);
  return readable;
}

// ---------------------------------------------------------------------------
// Main PoC
// ---------------------------------------------------------------------------

async function main() {
  console.log("╔══════════════════════════════════════════════════════════════╗");
  console.log("║  PoC: Canton transaction_uuid / preparedTransactionHash    ║");
  console.log("╚══════════════════════════════════════════════════════════════╝\n");

  // ─── Phase 0: Setup ────────────────────────────────────────────────
  console.log("─── Phase 0: Setup ───────────────────────────────────────────\n");

  await uploadDar(DAR_PATH);
  console.log("[setup] DAR uploaded");

  const issuer = await allocateParty("TxUuidIssuer");
  const depositor = await allocateParty("TxUuidDepositor");
  console.log(`[setup] Issuer:    ${issuer}`);
  console.log(`[setup] Depositor: ${depositor}`);

  await createUser(USER_ID, issuer, [depositor]);

  const packageId = packageIdFromTemplateId(VaultOrchestrator.templateIdWithPackageId);
  const caip2Id = chainIdHexToCaip2(
    "0000000000000000000000000000000000000000000000000000000000aa36a7",
  );
  const vaultAddress = deriveDepositAddress(MPC_ROOT_PUBLIC_KEY, packageId, "root", caip2Id);
  const evmParams = buildSampleEvmParams(vaultAddress);

  const orchResult = await createContract(USER_ID, [issuer], VAULT_ORCHESTRATOR, {
    issuer,
    mpcPublicKey: MPC_PUB_KEY_SPKI,
    vaultAddress: evmParams.args[0],
  });
  const firstEvent = orchResult.transaction.events?.[0];
  const orchCid =
    firstEvent && "CreatedEvent" in firstEvent ? firstEvent.CreatedEvent.contractId : undefined;
  if (!orchCid) throw new Error("Failed to get VaultOrchestrator contract ID");
  console.log(`[setup] Orchestrator CID: ${orchCid}`);

  // ─── Phase 1: Prepare (User gets transaction_uuid BEFORE execution) ─
  console.log("\n─── Phase 1: Prepare (Interactive Submission) ─────────────────\n");

  const commandId = crypto.randomUUID();
  console.log(`[user] commandId: ${commandId}`);

  const { data: prepareData, error: prepareError } = await client.POST(
    "/v2/interactive-submission/prepare",
    {
      body: {
        userId: USER_ID,
        commandId,
        commands: [
          {
            ExerciseCommand: {
              templateId: VAULT_ORCHESTRATOR,
              contractId: orchCid,
              choice: "RequestEvmDeposit",
              choiceArgument: {
                requester: depositor,
                path: depositor,
                evmParams,
              },
            },
          },
        ],
        actAs: [issuer, depositor],
        readAs: [issuer, depositor],
        synchronizerId: "",
        packageIdSelectionPreference: [],
        verboseHashing: true,
      } as components["schemas"]["JsPrepareSubmissionRequest"],
    },
  );

  if (prepareError || !prepareData) {
    console.error("[user] Prepare FAILED:", JSON.stringify(prepareError, null, 2));
    console.log("\n[FALLBACK] Prepare failed — testing with normal submit-and-wait instead.\n");
    await fallbackFlow(orchCid, depositor, evmParams, issuer);
    return;
  }

  console.log("[user] Prepare SUCCEEDED");
  console.log(`[user] preparedTransactionHash: ${prepareData.preparedTransactionHash}`);
  console.log(`[user] hashingSchemeVersion:     ${prepareData.hashingSchemeVersion}`);

  if (prepareData.preparedTransaction) {
    console.log(
      `[user] preparedTransaction (length): ${prepareData.preparedTransaction.length} chars`,
    );

    // Extract all UUIDs from the protobuf blob
    const allUuids = extractAllUuids(prepareData.preparedTransaction);
    console.log(`[user] UUIDs found in preparedTransaction blob (${allUuids.length}):`);
    for (const uuid of allUuids) {
      const isCommandId = uuid === commandId;
      console.log(
        `       ${uuid}${isCommandId ? "  ← commandId (user-provided)" : "  ← transaction_uuid (Canton-generated)"}`,
      );
    }

    // Dump all readable strings for inspection
    const readable = dumpReadableStrings(prepareData.preparedTransaction);
    console.log(`[user] Readable strings in preparedTransaction blob:`);
    for (const s of readable) {
      console.log(`       "${s}"`);
    }
  }

  if (prepareData.hashingDetails) {
    console.log(`[user] hashingDetails:\n${prepareData.hashingDetails}`);
  }

  // ─── Phase 2: Execute (User submits prepared tx to the chain) ──────
  console.log("\n─── Phase 2: Execute (Interactive Submission) ─────────────────\n");

  const submissionId = crypto.randomUUID();
  console.log(`[user] submissionId: ${submissionId}`);

  // Try executeAndWait first — sandbox may auto-sign for internal keys
  const { data: executeData, error: executeError } = await client.POST(
    "/v2/interactive-submission/executeAndWait",
    {
      body: {
        preparedTransaction: prepareData.preparedTransaction,
        partySignatures: { signatures: [] },
        deduplicationPeriod: { Empty: {} },
        submissionId,
        userId: USER_ID,
        hashingSchemeVersion: prepareData.hashingSchemeVersion,
      } as components["schemas"]["JsExecuteSubmissionAndWaitRequest"],
    },
  );

  let committedUpdateId: string | undefined;
  let committedOffset: number | undefined;

  if (executeError || !executeData) {
    console.error("[user] ExecuteAndWait FAILED:", JSON.stringify(executeError, null, 2));

    // Try executeAndWaitForTransaction (may handle signing differently)
    console.log("[user] Trying executeAndWaitForTransaction...");
    const { data: execTxData, error: execTxError } = await client.POST(
      "/v2/interactive-submission/executeAndWaitForTransaction",
      {
        body: {
          preparedTransaction: prepareData.preparedTransaction,
          partySignatures: { signatures: [] },
          deduplicationPeriod: { Empty: {} },
          submissionId: crypto.randomUUID(),
          userId: USER_ID,
          hashingSchemeVersion: prepareData.hashingSchemeVersion,
        } as components["schemas"]["JsExecuteSubmissionAndWaitForTransactionRequest"],
      },
    );

    if (execTxError || !execTxData) {
      console.error(
        "[user] ExecuteAndWaitForTransaction also FAILED:",
        JSON.stringify(execTxError, null, 2),
      );
      console.log(
        "\n[FALLBACK] Interactive execution failed (likely needs external signing keys).",
      );
      console.log("[FALLBACK] Running fallback with normal submit-and-wait...\n");
      await fallbackFlow(orchCid, depositor, evmParams, issuer);
      return;
    }

    // executeAndWaitForTransaction succeeded
    const tx = execTxData.transaction;
    committedUpdateId = tx.updateId;
    committedOffset = tx.offset;
    console.log("[user] ExecuteAndWaitForTransaction SUCCEEDED");
    logTransactionMetadata(tx, "user");
  } else {
    // executeAndWait succeeded
    committedUpdateId = executeData.updateId;
    committedOffset = executeData.completionOffset;
    console.log("[user] ExecuteAndWait SUCCEEDED");
    console.log(`[user] updateId:          ${executeData.updateId}`);
    console.log(`[user] completionOffset:  ${executeData.completionOffset}`);
  }

  // ─── Phase 3: MPC observes the update stream ──────────────────────
  console.log("\n─── Phase 3: MPC Observes Update Stream ──────────────────────\n");

  await observeAndCompare(
    committedOffset - 1,
    [issuer, depositor],
    prepareData.preparedTransactionHash,
    committedUpdateId,
  );

  // ─── Summary ──────────────────────────────────────────────────────
  printSummary(prepareData, committedUpdateId);
}

/**
 * Fallback: use normal submit-and-wait, then observe the update stream.
 * This still tests what metadata is visible to the MPC.
 */
async function fallbackFlow(
  orchCid: string,
  depositor: string,
  evmParams: ReturnType<typeof buildSampleEvmParams>,
  issuer: string,
) {
  console.log("─── Fallback: Normal Submit + Observe ────────────────────────\n");

  const offsetBefore = await getLedgerEnd();

  const result = await exerciseChoice(
    USER_ID,
    [issuer, depositor],
    VAULT_ORCHESTRATOR,
    orchCid,
    "RequestEvmDeposit",
    { requester: depositor, path: depositor, evmParams },
  );

  const tx = result.transaction;
  console.log("[fallback] Submit-and-wait SUCCEEDED");
  logTransactionMetadata(tx, "fallback");

  // Now observe via update stream (as MPC would)
  console.log("\n[mpc] Observing update stream...");
  await observeAndCompare(offsetBefore, [issuer, depositor], undefined, tx.updateId);

  console.log("\n─── Fallback Summary ─────────────────────────────────────────\n");
  console.log("The normal submit-and-wait path does NOT use the Interactive Submission");
  console.log("Service externally, so externalTransactionHash is likely empty.");
  console.log("To test the full prepare→execute→observe flow, external party keys");
  console.log("must be configured on the Canton participant.\n");
  console.log("Key findings from fallback:");
  console.log(`  updateId:                 ${tx.updateId}`);
  console.log(`  commandId:                ${tx.commandId}`);
  console.log(`  externalTransactionHash:  ${tx.externalTransactionHash ?? "(empty)"}`);
}

/**
 * Log all metadata fields from a JsTransaction.
 */
function logTransactionMetadata(tx: components["schemas"]["JsTransaction"], label: string): void {
  console.log(`[${label}] Transaction metadata:`);
  console.log(`  updateId:                 ${tx.updateId}`);
  console.log(`  commandId:                ${tx.commandId}`);
  console.log(`  workflowId:               ${tx.workflowId || "(empty)"}`);
  console.log(`  effectiveAt:              ${tx.effectiveAt}`);
  console.log(`  offset:                   ${tx.offset}`);
  console.log(`  synchronizerId:           ${tx.synchronizerId}`);
  console.log(`  recordTime:               ${tx.recordTime}`);
  console.log(`  externalTransactionHash:  ${tx.externalTransactionHash ?? "(empty)"}`);
  console.log(`  traceContext:             ${JSON.stringify(tx.traceContext)}`);
  console.log(`  events count:             ${tx.events?.length ?? 0}`);

  for (const event of tx.events ?? []) {
    if ("CreatedEvent" in event) {
      const ce = event.CreatedEvent;
      console.log(`  [CreatedEvent] templateId=${ce.templateId} contractId=${ce.contractId}`);
    } else if ("ArchivedEvent" in event) {
      const ae = event.ArchivedEvent;
      console.log(`  [ArchivedEvent] templateId=${ae.templateId} contractId=${ae.contractId}`);
    }
  }
}

/**
 * Observe the update stream and compare with user-provided identifiers.
 */
async function observeAndCompare(
  beginExclusive: number,
  parties: string[],
  userPreparedHash: string | undefined,
  expectedUpdateId: string | undefined,
) {
  const updates = await getUpdates(beginExclusive, parties, 3000);
  console.log(`[mpc] Received ${updates.length} update(s) from stream`);

  for (const item of updates) {
    const update = item.update;
    if (!("Transaction" in update)) {
      console.log(`[mpc] Non-transaction update: ${Object.keys(update).join(", ")}`);
      continue;
    }

    const tx = update.Transaction.value;
    console.log(`\n[mpc] ── Transaction found ──`);
    logTransactionMetadata(tx, "mpc");

    // Correlation check 1: externalTransactionHash == preparedTransactionHash
    if (userPreparedHash) {
      const match = tx.externalTransactionHash === userPreparedHash;
      console.log(`\n[mpc] Correlation check: externalTransactionHash == preparedTransactionHash`);
      console.log(`  User provided:  ${userPreparedHash}`);
      console.log(`  MPC observed:   ${tx.externalTransactionHash ?? "(empty)"}`);
      console.log(`  Match: ${match ? "✓ YES" : "✗ NO"}`);
    }

    // Correlation check 2: updateId match
    if (expectedUpdateId) {
      const match = tx.updateId === expectedUpdateId;
      console.log(`\n[mpc] Correlation check: updateId`);
      console.log(`  Expected: ${expectedUpdateId}`);
      console.log(`  Observed: ${tx.updateId}`);
      console.log(`  Match: ${match ? "✓ YES" : "✗ NO"}`);
    }

    // Dump the full transaction as JSON for manual inspection
    console.log(`\n[mpc] Full transaction JSON (for manual inspection):`);
    console.log(JSON.stringify(tx, null, 2));
  }
}

/**
 * Print final summary with conclusions.
 */
function printSummary(
  prepareData: components["schemas"]["JsPrepareSubmissionResponse"],
  committedUpdateId: string | undefined,
) {
  console.log("\n╔══════════════════════════════════════════════════════════════╗");
  console.log("║  Summary                                                    ║");
  console.log("╚══════════════════════════════════════════════════════════════╝\n");

  console.log("Identifiers available at each phase:\n");
  console.log("  PREPARE (user, before execution):");
  console.log(`    preparedTransactionHash: ${prepareData.preparedTransactionHash}`);
  console.log(
    `    preparedTransaction:     ${prepareData.preparedTransaction ? "(base64 blob)" : "(empty)"}`,
  );
  console.log(`    hashingSchemeVersion:     ${prepareData.hashingSchemeVersion}`);

  console.log("\n  COMMITTED (on chain, after execution):");
  console.log(`    updateId:                ${committedUpdateId ?? "(not available)"}`);

  console.log("\n  Correlation mechanism:");
  console.log("    preparedTransactionHash (from prepare) ↔ externalTransactionHash (from tx)");
  console.log("    If they match: user can provide preparedTransactionHash before execution,");
  console.log("    MPC reads externalTransactionHash from the committed transaction,");
  console.log("    and both values can be independently compared — same pattern as packageId.\n");
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
