import { describe, it, expect } from "vitest";
import { encodeAbiParameters } from "viem";

// ---------------------------------------------------------------------------
// Cross-language vectors (must match Daml TestAbi.daml)
// Generated by viem encodeAbiParameters — these are the ground truth.
// ---------------------------------------------------------------------------

const VITALIK = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" as const;

const VECTORS = {
  // --- Static types ---
  uint256_1000: "0x00000000000000000000000000000000000000000000000000000000000003e8",
  bool_true: "0x0000000000000000000000000000000000000000000000000000000000000001",
  bool_false: "0x0000000000000000000000000000000000000000000000000000000000000000",
  address_vitalik: "0x000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045",
  bytes32_deadbeef: "0xdeadbeef00000000000000000000000000000000000000000000000000000000",
  tuple_uint_addr_bool:
    "0x" +
    "00000000000000000000000000000000000000000000000000000000000003e8" +
    "000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045" +
    "0000000000000000000000000000000000000000000000000000000000000001",
  tuple_uint_uint:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000064" +
    "00000000000000000000000000000000000000000000000000000000000000c8",
  int256_neg1: "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
  int256_neg128: "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80",
  uint8_255: "0x00000000000000000000000000000000000000000000000000000000000000ff",
  bytes4_deadbeef: "0xdeadbeef00000000000000000000000000000000000000000000000000000000",
  fixed_array_uint256_3:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000001" +
    "0000000000000000000000000000000000000000000000000000000000000002" +
    "0000000000000000000000000000000000000000000000000000000000000003",

  // --- Dynamic types ---
  tuple_uint_string:
    "0x" +
    "000000000000000000000000000000000000000000000000000000000000002a" +
    "0000000000000000000000000000000000000000000000000000000000000040" +
    "0000000000000000000000000000000000000000000000000000000000000005" +
    "48656c6c6f000000000000000000000000000000000000000000000000000000",
  single_string:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "000000000000000000000000000000000000000000000000000000000000000b" +
    "48656c6c6f20576f726c64000000000000000000000000000000000000000000",
  dynamic_array_uint256:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000003" +
    "000000000000000000000000000000000000000000000000000000000000000a" +
    "0000000000000000000000000000000000000000000000000000000000000014" +
    "000000000000000000000000000000000000000000000000000000000000001e",
  uint_string_uint:
    "0x" +
    "000000000000000000000000000000000000000000000000000000000000002a" +
    "0000000000000000000000000000000000000000000000000000000000000060" +
    "0000000000000000000000000000000000000000000000000000000000000063" +
    "0000000000000000000000000000000000000000000000000000000000000005" +
    "48656c6c6f000000000000000000000000000000000000000000000000000000",

  // --- Additional edge cases ---
  int256_zero: "0x0000000000000000000000000000000000000000000000000000000000000000",
  int256_min_int64: "0xffffffffffffffffffffffffffffffffffffffffffffffff8000000000000000",
  bytes1_ab: "0xab00000000000000000000000000000000000000000000000000000000000000",
  tuple_uint_bool_false:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000000" +
    "0000000000000000000000000000000000000000000000000000000000000000",
  bytes_dynamic_aabbcc:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000003" +
    "aabbcc0000000000000000000000000000000000000000000000000000000000",
  empty_string:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000000",
  string_32bytes:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "4142434445464748494a4b4c4d4e4f505152535455565758595a313233343536",
  uint_dynamic_array:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000007" +
    "0000000000000000000000000000000000000000000000000000000000000040" +
    "0000000000000000000000000000000000000000000000000000000000000002" +
    "0000000000000000000000000000000000000000000000000000000000000064" +
    "00000000000000000000000000000000000000000000000000000000000000c8",
  empty_dynamic_array:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000000",
  single_elem_dynamic_array:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "0000000000000000000000000000000000000000000000000000000000000001" +
    "000000000000000000000000000000000000000000000000000000000000002a",

  // --- Nested tuple (static inner tuple is flattened by ABI) ---
  nested_tuple_uint_addr_bool:
    "0x" +
    "000000000000000000000000000000000000000000000000000000000000002a" +
    "000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045" +
    "0000000000000000000000000000000000000000000000000000000000000001",

  // --- Multiple dynamic types (two offset pointers in head) ---
  two_strings:
    "0x" +
    "0000000000000000000000000000000000000000000000000000000000000040" +
    "0000000000000000000000000000000000000000000000000000000000000080" +
    "0000000000000000000000000000000000000000000000000000000000000005" +
    "48656c6c6f000000000000000000000000000000000000000000000000000000" +
    "0000000000000000000000000000000000000000000000000000000000000005" +
    "576f726c64000000000000000000000000000000000000000000000000000000",

  // --- Original edge cases ---
  uint256_zero: "0x0000000000000000000000000000000000000000000000000000000000000000",
  uint256_max_int64: "0x0000000000000000000000000000000000000000000000007fffffffffffffff",
} as const;

// ---------------------------------------------------------------------------
// Tests: verify viem encodes to exactly the hardcoded hex vectors.
// The Daml side (TestAbi.daml) decodes these same hex vectors and asserts
// the same expected values — that's the cross-validation.
// ---------------------------------------------------------------------------

describe("ABI encoding vectors (cross-language ground truth)", () => {
  // --- Static types ---
  it("uint256(1000)", () => {
    expect(encodeAbiParameters([{ type: "uint256" }], [1000n])).toBe(VECTORS.uint256_1000);
  });
  it("bool(true)", () => {
    expect(encodeAbiParameters([{ type: "bool" }], [true])).toBe(VECTORS.bool_true);
  });
  it("bool(false)", () => {
    expect(encodeAbiParameters([{ type: "bool" }], [false])).toBe(VECTORS.bool_false);
  });
  it("address", () => {
    expect(encodeAbiParameters([{ type: "address" }], [VITALIK])).toBe(VECTORS.address_vitalik);
  });
  it("bytes32", () => {
    expect(
      encodeAbiParameters(
        [{ type: "bytes32" }],
        ["0xdeadbeef00000000000000000000000000000000000000000000000000000000"],
      ),
    ).toBe(VECTORS.bytes32_deadbeef);
  });
  it("(uint256, address, bool)", () => {
    expect(
      encodeAbiParameters(
        [{ type: "uint256" }, { type: "address" }, { type: "bool" }],
        [1000n, VITALIK, true],
      ),
    ).toBe(VECTORS.tuple_uint_addr_bool);
  });
  it("(uint256, uint256)", () => {
    expect(encodeAbiParameters([{ type: "uint256" }, { type: "uint256" }], [100n, 200n])).toBe(
      VECTORS.tuple_uint_uint,
    );
  });
  it("int256(-1)", () => {
    expect(encodeAbiParameters([{ type: "int256" }], [-1n])).toBe(VECTORS.int256_neg1);
  });
  it("int256(-128)", () => {
    expect(encodeAbiParameters([{ type: "int256" }], [-128n])).toBe(VECTORS.int256_neg128);
  });
  it("uint8(255)", () => {
    expect(encodeAbiParameters([{ type: "uint8" }], [255])).toBe(VECTORS.uint8_255);
  });
  it("bytes4(0xdeadbeef)", () => {
    expect(encodeAbiParameters([{ type: "bytes4" }], ["0xdeadbeef"])).toBe(VECTORS.bytes4_deadbeef);
  });
  it("uint256[3]([1, 2, 3])", () => {
    expect(encodeAbiParameters([{ type: "uint256[3]" }], [[1n, 2n, 3n]])).toBe(
      VECTORS.fixed_array_uint256_3,
    );
  });

  // --- Dynamic types ---
  it("(uint256, string) = (42, 'Hello')", () => {
    expect(encodeAbiParameters([{ type: "uint256" }, { type: "string" }], [42n, "Hello"])).toBe(
      VECTORS.tuple_uint_string,
    );
  });
  it("(string) = ('Hello World')", () => {
    expect(encodeAbiParameters([{ type: "string" }], ["Hello World"])).toBe(VECTORS.single_string);
  });
  it("(uint256[]) = ([10, 20, 30])", () => {
    expect(encodeAbiParameters([{ type: "uint256[]" }], [[10n, 20n, 30n]])).toBe(
      VECTORS.dynamic_array_uint256,
    );
  });
  it("(uint256, string, uint256) = (42, 'Hello', 99)", () => {
    expect(
      encodeAbiParameters(
        [{ type: "uint256" }, { type: "string" }, { type: "uint256" }],
        [42n, "Hello", 99n],
      ),
    ).toBe(VECTORS.uint_string_uint);
  });

  // --- Additional edge cases ---
  it("int256(0)", () => {
    expect(encodeAbiParameters([{ type: "int256" }], [0n])).toBe(VECTORS.int256_zero);
  });
  it("int256(-2^63) — min Int64", () => {
    expect(encodeAbiParameters([{ type: "int256" }], [-9223372036854775808n])).toBe(
      VECTORS.int256_min_int64,
    );
  });
  it("bytes1(0xab)", () => {
    expect(encodeAbiParameters([{ type: "bytes1" }], ["0xab"])).toBe(VECTORS.bytes1_ab);
  });
  it("(uint256, bool) = (0, false)", () => {
    expect(encodeAbiParameters([{ type: "uint256" }, { type: "bool" }], [0n, false])).toBe(
      VECTORS.tuple_uint_bool_false,
    );
  });
  it("bytes — dynamic 0xaabbcc", () => {
    expect(encodeAbiParameters([{ type: "bytes" }], ["0xaabbcc"])).toBe(
      VECTORS.bytes_dynamic_aabbcc,
    );
  });
  it("string — empty", () => {
    expect(encodeAbiParameters([{ type: "string" }], [""])).toBe(VECTORS.empty_string);
  });
  it("string — exactly 32 bytes", () => {
    expect(encodeAbiParameters([{ type: "string" }], ["ABCDEFGHIJKLMNOPQRSTUVWXYZ123456"])).toBe(
      VECTORS.string_32bytes,
    );
  });
  it("(uint256, uint256[]) = (7, [100, 200])", () => {
    expect(
      encodeAbiParameters([{ type: "uint256" }, { type: "uint256[]" }], [7n, [100n, 200n]]),
    ).toBe(VECTORS.uint_dynamic_array);
  });
  it("uint256[] — empty array", () => {
    expect(encodeAbiParameters([{ type: "uint256[]" }], [[]])).toBe(VECTORS.empty_dynamic_array);
  });
  it("uint256[] — single element [42]", () => {
    expect(encodeAbiParameters([{ type: "uint256[]" }], [[42n]])).toBe(
      VECTORS.single_elem_dynamic_array,
    );
  });
  // --- Nested tuple ---
  it("(uint256, (address, bool)) — nested static tuple flattened", () => {
    expect(
      encodeAbiParameters(
        [
          { type: "uint256" },
          {
            type: "tuple",
            components: [
              { type: "address", name: "addr" },
              { type: "bool", name: "flag" },
            ],
          },
        ],
        [42n, { addr: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045", flag: true }],
      ),
    ).toBe(VECTORS.nested_tuple_uint_addr_bool);
  });

  // --- Multiple dynamic types ---
  it("(string, string) = ('Hello', 'World') — two offset pointers", () => {
    expect(encodeAbiParameters([{ type: "string" }, { type: "string" }], ["Hello", "World"])).toBe(
      VECTORS.two_strings,
    );
  });

  it("uint256(0)", () => {
    expect(encodeAbiParameters([{ type: "uint256" }], [0n])).toBe(VECTORS.uint256_zero);
  });
  it("uint256(2^63 - 1) — max Int64", () => {
    expect(encodeAbiParameters([{ type: "uint256" }], [9223372036854775807n])).toBe(
      VECTORS.uint256_max_int64,
    );
  });
});
